<?php 
    require 'index.php';
?>
<!DOCTYPE html>
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="css/cv.css">
        <title>CV HTML</title>
    </head>
    
<body>
    <main>
        
    <div id="name">
        <h1>
            <?php 
                echo $tab['nom'], $tab["prenom"];
            ?>
        </h1>
            <p>Intitulé du poste</p>
    </div>
    
    <section id="big">
        <section id="left">
            <h1>INFORMATIONS</h1>
                <h3>Contact</h3>
                
                    <p>Email</p>
                        <?=$tab["email"]?>
                    <p>Téléphone</p>
                        <?=$tab["tel"]?>
                    <p>LinkedIn</p>
                        <?=$tab["linkedin"]?>
                
                <h3>Biographie</h3>
                    <?=$tab["bio"]?>
                <h3>Loisirs</h3>
                     <ul>
                        <li><?=$tab2["loisir1"]?></li>
                        <li><?=$tab2["loisir2"]?></li>
                        <li><?=$tab2["loisir3"]?></li>
                        <li><?=$tab2["loisir4"]?></li>
                    </ul>
            
        </section>
        <section id="right">
            <h1>COMPETENCES</h1>
                <h3>Langages de Programmation</h3>
                    <ul>
                        <?php foreach($tab["lang"] as $lang) { ?>

                            <li><?= $lang; ?></li>

                        <?php }; ?>
                    </ul>
                    
                <h3>Frameworks & Librairies</h3>
                    <ul>
                        <?php foreach($tab["frameworks"] as $framework) { ?>

                            <li><?= $framework; ?></li>

                        <?php }; ?>
                    </ul>
                    
                <h3>Logiciels</h3>
                     <ul>
                        <?php foreach($tab["software"] as $software) { ?>

                            <li><?= $software; ?></li>

                        <?php }; ?>
                    </ul>
                    
                <h3>Langues</h3>
                     <ul>
                        <?php foreach($tab["language"] as $language) { ?>

                            <li><?= $language ?></li>

                        <?php }; ?>
                    </ul>
            
        </section>
    </section>
    </main>   
</body>
    
</html>