<!DOCTYPE html>
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="css/cv.css">
        <title>CV HTML</title>
    </head>
    
<body>
    <main>
        
    <div id="name">
        <h1>
            
        </h1>
            <p>Intitulé du poste</p>
    </div>
    
    <section id="big">
        <section id="left">
            <h1>INFORMATIONS</h1>
                <h3>Contact</h3>
                
                    <p>Email</p>
                        
                    <p>Téléphone</p>
                        
                    <p>LinkedIn</p>
                        
                
                <h3>Biographie</h3>
                    
                <h3>Loisirs</h3>
                     <ul>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
            
        </section>
        <section id="right">
            <h1>COMPETENCES</h1>
                <h3>Langages de Programmation</h3>
                    <ul>
                        <li></li>
                    </ul>
                    
                <h3>Frameworks & Librairies</h3>
                    <ul>
                        <li></li>
                    </ul>
                    
                <h3>Logiciels</h3>
                     <ul>
                        <li></li>
                    </ul>
                    
                <h3>Langues</h3>
                     <ul>
                        <li></li>
                    </ul>
            
        </section>
    </section>
    </main>   
</body>
    
</html>