<h3>INFORMATIONS</h3>
            <p>Nom</p>
                <input type="text" name="nom"/>
            <p>Prenom</p>
                <input type="text" name="prenom"/>
            <p>Email</p>
                <input type="text" name ="email"/>
            <p>Telephone</p>
                <input type="text" name="tel"/>
            <p>LinkedIn</p>
                <input type="text" name ="linkedin"/>
            <p>Biographie</p>
                <textarea type="textarea" id="bio" name="bio"></textarea>
            <p>Loisir 1</p>
                <input type="text" name="loisir1"/>
            <p>Loisir 2</p>
                <input type="text" name="loisir2"/>
            <p>Loisir 3</p>
                <input type="text" name="loisir3"/>
            <p>Loisir 4</p>
                <input type="text" name="loisir4"/>
                
            <?php require 'lang.phtml'?>