<h4>Langages de Programmation</h4>
                    <dl>
                    <dt>
                    <input type="checkbox" name="html[]">
                        <label>HTML</label>
                    </dt>   
                    <dt>
                    <input type="checkbox" name="css[]">
                        <label>CSS</label>
                    </dt>
                    <dt>
                    <input type="checkbox" name="javascript[]">
                        <label>JavaScript</label>
                    </dt>
                    <dt>
                    <input type="checkbox" name="php[]">
                        <label>PHP</label>
                    </dt>
                    <dt>
                    <input type="checkbox" name="sql[]">
                    <label>SQL</label>
                    </dt>
                    </dl>