<h4>LANGUES</h4>
                <dl>
                <dt>
                <input type="checkbox" name="Français[]">
                    <label>Français</label>
                </dt>
                <dt>
                <input type="checkbox" name="Anglais[]">
                    <label>Anglais</label>
                </dt>
                <dt>
                <input type="checkbox" name="Arabe[]">
                    <label>Arabe</label>
                </dt>
                <dt>
                <input type="checkbox" name="Breton[]">
                    <label>Breton</label>
                </dt>
                <dt>
               <input type="checkbox" name="Espagnol[]">
               <label>Espagnol</label>
               </dt>
                </dl>