<h4>Logiciels</h4>
                    <dl>
                    <dt>
                    <input type="checkbox" name="photoshop[]">
                        <label>Photoshop</label>
                    </dt>   
                    <dt>
                    <input type="checkbox" name="illustrator[]">
                        <label>Illustrator</label>
                    </dt>
                    <dt>
                    <input type="checkbox" name="xd[]">
                        <label>XD</label>
                    </dt>
                    <dt>
                    <input type="checkbox" name="figma[]">
                        <label>Figma</label>
                    </dt>
                    </dl>